name: Pipeline
on: push

jobs:
  build:
    name: Validate,  Test & Build 
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Initialize
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Prettier
      run: npm run prettier:check
      
    - name: Test
      run: npm run test -- --testResultsProcessor=\"jest-junit\"
      
    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
      
    - name: Build
      run: npm run build
    
    - name: Save Build 
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build/
      
  web-audit:
    name: Web Audit
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install, build
        run: npm install

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
          
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
